name: FastAPI CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug tree
        run: |
          pwd
          ls -la
          echo "---- app ----"
          ls -la app || true
          echo "---- tests ----"
          ls -la tests || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze | grep -E 'fastapi|starlette|httpx|pytest' || true

      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Run pytest
        run: python -m pytest tests/test_main.py -q -rA
