name: FastAPI CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest ./tests/test_main.py -q
