name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to print"
        required: true
        default: "Hello from manual workflow"
      run_extra:
        description: "Run extra step?"
        type: boolean
        default: false

jobs:
  echo:
    runs-on: macos-latest
    steps:
      - name: Print message
        run: echo "${{ github.event.inputs.message }}"
      - name: Extra step
        if: ${{ github.event.inputs.run_extra == 'true' }}
        run: echo "Running extra step!"
