name: Secret Verification

on:
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if secret is missing
        run: |
          if [ -z "${MY_SECRET}" ]; then
            echo "Secret MY_SECRET is missing"
            exit 1
          fi
          echo "Secret MY_SECRET is present"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Show SHA256 of secret (safe verification)
        run: |
          echo -n "$MY_SECRET" | sha256sum | awk '{print "MY_SECRET_SHA256:", $1}'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Optional extra hardening with explicit masking
        run: |
          # GitHub already masks ${{ secrets.* }} automatically
          # add-mask helps if your script transforms the secret
          echo "::add-mask::${MY_SECRET}"
          echo "Mask is in place"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}